CriasApp/Controllers/RegistroCriasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CriasApp.Models;

namespace CriasApp.Controllers
{
    public class RegistroCriasController : Controller
    {
        private readonly CriasContext _context;

        public RegistroCriasController(CriasContext context)
        {
            _context = context;
        }

        // GET: RegistroCrias
        public async Task<IActionResult> Index()
        {
              return _context.RegistroCrias != null ? 
                          View(await _context.RegistroCrias.ToListAsync()) :
                          Problem("Entity set 'CriasContext.RegistroCrias'  is null.");
        }

        // GET: RegistroCrias/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.RegistroCrias == null)
            {
                return NotFound();
            }

            var registroCria = await _context.RegistroCrias
                .FirstOrDefaultAsync(m => m.IdCria == id);
            if (registroCria == null)
            {
                return NotFound();
            }

            return View(registroCria);
        }

        // GET: RegistroCrias/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: RegistroCrias/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdCria,Fecha,Peso,Costo,Nombre,Descripcion")] RegistroCria registroCria)
        {
            if (ModelState.IsValid)
            {
                _context.Add(registroCria);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(registroCria);
        }

        // GET: RegistroCrias/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.RegistroCrias == null)
            {
                return NotFound();
            }

            var registroCria = await _context.RegistroCrias.FindAsync(id);
            if (registroCria == null)
            {
                return NotFound();
            }
            return View(registroCria);
        }

        // POST: RegistroCrias/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdCria,Fecha,Peso,Costo,Nombre,Descripcion")] RegistroCria registroCria)
        {
            if (id != registroCria.IdCria)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(registroCria);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RegistroCriaExists(registroCria.IdCria))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(registroCria);
        }

        // GET: RegistroCrias/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.RegistroCrias == null)
            {
                return NotFound();
            }

            var registroCria = await _context.RegistroCrias
                .FirstOrDefaultAsync(m => m.IdCria == id);
            if (registroCria == null)
            {
                return NotFound();
            }

            return View(registroCria);
        }

        // POST: RegistroCrias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.RegistroCrias == null)
            {
                return Problem("Entity set 'CriasContext.RegistroCrias'  is null.");
            }
            var registroCria = await _context.RegistroCrias.FindAsync(id);
            if (registroCria != null)
            {
                _context.RegistroCrias.Remove(registroCria);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RegistroCriaExists(int id)
        {
          return (_context.RegistroCrias?.Any(e => e.IdCria == id)).GetValueOrDefault();
        }
    }
}

CriasApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CriasApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CriasApp.styles.css" asp-append-version="true" />

    <!-- Carga la librería de Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- Carga la librería de jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>

    <!-- Carga la librería de Bootstrap -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>


</head>

<style>

    #btnLogin:hover {
        box-shadow: 2.5px 2.5px rgba(0,0,0,0.75);
        -webkit-box-shadow: 2.5px 2.5px rgba(0,0,0,0.75);
        -moz-box-shadow: 2.5px 2.5px rgba(0,0,0,0.75);
    } 

    .footer {
        position: fixed;
        bottom: 0;
        width: 100%;
        height: 50px;
        color: white;
        text-align: center;
    }

</style>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CriasApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse">
                    <ul class="navbar-nav flex-grow-1" style="display: flex; justify-content: space-between;">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="RegistroCrias" asp-action="Index">Inicio</a>
                            </li>
                        }
                        @*@if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                
                            </li>
                        }*@

                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CriasApp 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>